### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [144] at entry 0 and [3] at entry 6

### ISSUE THREAD

**Issue by goforit6** [anishathalye/ribosome#1]
RuntimeError: stack expects each tensor to be equal size, but got [144] at entry 0 and [3] at entry 6

**Comment by anishathalye** [comment]
How can I reproduce this error?

I suspect that the data format is erroneous and one of the hashes has 3 bytes instead of the expected 144.

**Comment by goforit6** [comment]
Just run "python train.py --train-data coco-train.csv --val-data coco-val.csv --epochs 3 --batch-size 10 --verbose" for a while.

**Comment by anishathalye** [comment]
If I clone the repo, download the data from GitHub, and run that command above, it works.

Is your data corrupted? Here are sha256 hashes you can compare against:

```
a0a3a1508cb6782baf7437e579e016d2f38f14c71d1bdad6b594d66cf41472a7  coco100x100.tar.gz
59609f3981459c8deaaaa6ce8ac2845689fd3783cff51234016f0ae2173b36c8  coco-train.csv
4e6c27524f84a09c978b91d3ac8bc62ee142a0d695272afab2c7f024f7cd628c  coco-val.csv
```

**Comment by goforit6** [comment]
Maybe, the data is too large, I deleted 80 percent of them, include coco100x100.tar.gz and csv files. but they are one-to-one.

**Comment by anishathalye** [comment]
Did you make a mistake when deleting data, such that it doesn’t fit the format anymore?

**Comment by goforit6** [comment]
I observed that every time it reported an error at the end of the last fast run, 
[coco-train.csv](https://github.com/anishathalye/ribosome/files/7776656/coco-train.csv)
although I have deleted the last data.

**Comment by anishathalye** [comment]
Can't reproduce it with that file either.

**Comment by goforit6** [comment]
I found an abnormal data in coco-train.csv which hash is "#NAME?", you can search "000000538223.jpg" to find it.
![20211227210107](https://user-images.githubusercontent.com/43409013/147474204-bdd8f9dc-0a9c-4198-b8b7-6ac72f924c63.png)

**Comment by anishathalye** [comment]
There is no issue with the data. That hash starts with a "+" (as base64-encoded values are allowed to) and Excel is interpreting it weirdly. Excel is probably doing something weird when this file is saved, rather than preserving the original value. Try processing the file using a tool that doesn't mess with the data. If you want to keep the first 1000 lines, you can do something like `head -n 1000 < coco-train.csv > coco-train-subset.csv`.

**Comment by goforit6** [comment]
Ok, I'll close it, thanks.
